$background = fff8f7
$onBackground = 3d2f31
$surface = fff8f7
$surfaceDim = ebd5d8
$surfaceBright = fff8f7
$surfaceContainerLowest = ffffff
$surfaceContainerLow = fff0f1
$surfaceContainer = fde9eb
$surfaceContainerHigh = f8e3e6
$surfaceContainerHighest = f4dde0
$onSurface = 3d2f31
$surfaceVariant = f4dde0
$onSurfaceVariant = 6c5b5e
$outline = 887679
$outlineVariant = c2adb0
$inverseSurface = 130c0e
$inverseOnSurface = a69a9b
$shadow = 000000
$scrim = 000000
$surfaceTint = 894d5b
$primary = 894d5b
$primaryDim = 7c414f
$onPrimary = fff7f7
$primaryContainer = f8acbc
$onPrimaryContainer = 612b39
$inversePrimary = f8acbc
$primaryFixed = f8acbc
$primaryFixedDim = e99fae
$onPrimaryFixed = 471725
$onPrimaryFixedVariant = 6b3442
$secondary = 76575d
$secondaryDim = 694b51
$onSecondary = fff7f7
$secondaryContainer = ffd9df
$onSecondaryContainer = 674a50
$secondaryFixed = ffd9df
$secondaryFixedDim = f3cad1
$onSecondaryFixed = 53383d
$onSecondaryFixedVariant = 725359
$tertiary = 745479
$tertiaryDim = 68486c
$onTertiary = fff7fb
$tertiaryContainer = fcd2fe
$onTertiaryContainer = 644569
$tertiaryFixed = fcd2fe
$tertiaryFixedDim = edc5f0
$onTertiaryFixed = 503355
$onTertiaryFixedVariant = 6f4f73
$error = a83836
$errorDim = 67040d
$onError = fff7f6
$errorContainer = fa746f
$onErrorContainer = 6e0a12
$primaryPaletteKeyColor = a56473
$secondaryPaletteKeyColor = 8f6e74
$tertiaryPaletteKeyColor = 8e6b91
$neutralPaletteKeyColor = 7f7475
$neutralVariantPaletteKeyColor = 857376
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = a56473
$secondary_paletteKeyColor = 8f6e74
$tertiary_paletteKeyColor = 8e6b91
$neutral_paletteKeyColor = 7f7475
$neutral_variant_paletteKeyColor = 857376
$term0 = a19997
$term1 = b42757
$term2 = c96245
$term3 = ae535e
$term4 = cd6d67
$term5 = b53e6d
$term6 = 9073b8
$term7 = 262022
$term8 = 100f0f
$term9 = d4406e
$term10 = f18062
$term11 = d06e79
$term12 = f78e87
$term13 = d65887
$term14 = b193da
$term15 = 2d2729
$rosewater = b26873
$flamingo = b4596c
$pink = ce5180
$mauve = a4006a
$red = a90045
$maroon = c02456
$peach = d83658
$yellow = c95b60
$green = c04800
$teal = 745ca0
$sky = b359a2
$sapphire = 8b61a9
$blue = a21d7d
$lavender = b7488e
$klink = bc6ca5
$klinkSelection = bc6ca6
$kvisited = c85c8b
$kvisitedSelection = c85c8b
$knegative = ea4f78
$knegativeSelection = ea4f79
$kneutral = ff8691
$kneutralSelection = ff8692
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = 3d2f31
$subtext1 = 6c5b5e
$subtext0 = 887679
$overlay2 = 968688
$overlay1 = a79899
$overlay0 = b6a9aa
$surface2 = c7bbbb
$surface1 = d8cece
$surface0 = ebe3e2
$base = fff8f7
$mantle = f5f0ef
$crust = efeaea
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
